#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxBox.MVC.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_Alerts.cshtml"
    using MaxBox.MVC.Infrastructure;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Alerts.cshtml")]
    public partial class Alerts : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Alerts()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\_Alerts.cshtml"
 if (TempData.GetAlerts().Any())
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"container alert-container\"");

WriteLiteral(">\r\n");

            
            #line 5 "..\..\Views\Shared\_Alerts.cshtml"
        
            
            #line default
            #line hidden
            
            #line 5 "..\..\Views\Shared\_Alerts.cshtml"
         foreach (var alert in TempData.GetAlerts())
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 197), Tuple.Create("\"", 246)
, Tuple.Create(Tuple.Create("", 205), Tuple.Create("alert", 205), true)
            
            #line 7 "..\..\Views\Shared\_Alerts.cshtml"
, Tuple.Create(Tuple.Create(" ", 210), Tuple.Create<System.Object, System.Int32>(alert.AlertClass
            
            #line default
            #line hidden
, 211), false)
, Tuple.Create(Tuple.Create(" ", 228), Tuple.Create("alert-dismissable", 229), true)
);

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dimiss=\"alert\"");

WriteLiteral(" aria-hidden=\"True\"");

WriteLiteral(">&times;</button>\r\n");

WriteLiteral("                ");

            
            #line 9 "..\..\Views\Shared\_Alerts.cshtml"
           Write(alert.Message);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 11 "..\..\Views\Shared\_Alerts.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 13 "..\..\Views\Shared\_Alerts.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
