#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxBox.MVC.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    #line 1 "..\..\Views\Shared\_Filters.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\Views\Shared\_Filters.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\_Filters.cshtml"
    using MaxBox.MVC.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Filters.cshtml")]
    public partial class Filters : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Filters()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Shared\_Filters.cshtml"
  
    var pageProcessData = (PageProcessData)ViewBag.PagingVM;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\Shared\_Filters.cshtml"
 if (pageProcessData != null)
{
    if (pageProcessData.Filters.Any())
    {

            
            #line default
            #line hidden
WriteLiteral("        <form");

WriteLiteral(" method=\"GET\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 13 "..\..\Views\Shared\_Filters.cshtml"
                
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Shared\_Filters.cshtml"
                 foreach (var filter in pageProcessData.Filters.Where(x => x.SelectList.Count() > 1))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 16 "..\..\Views\Shared\_Filters.cshtml"
                   Write(Html.Partial("_Filter", (object)filter.Label));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

            
            #line 18 "..\..\Views\Shared\_Filters.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </form>\r\n");

            
            #line 21 "..\..\Views\Shared\_Filters.cshtml"
    }
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
