#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxBox.MVC.Views.Shared
{
    
    #line 1 "..\..\Views\Shared\_Filter.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.IO;
    
    #line 2 "..\..\Views\Shared\_Filter.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 3 "..\..\Views\Shared\_Filter.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    
    #line 4 "..\..\Views\Shared\_Filter.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Views\Shared\_Filter.cshtml"
    using MaxBox.MVC.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Filter.cshtml")]
    public partial class Filter : System.Web.Mvc.WebViewPage<string>
    {
        public Filter()
        {
        }
        public override void Execute()
        {
            
            #line 7 "..\..\Views\Shared\_Filter.cshtml"
  
    var pageData = (PageProcessData)ViewBag.PageData;
    PropertyFilter filter = pageData.Filters.FirstOrDefault(x => x.Label.ToLower() == Model.ToLower());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\Shared\_Filter.cshtml"
 if (filter != null)
{
    SelectList listwithselect = null;
    string filterValue = pageData.Query[filter.PropertyName];
    if (filterValue != null)
    {
        listwithselect = new SelectList(filter.SelectList.Items, filter.SelectList.DataValueField, filter.SelectList.DataTextField, filterValue);
    }
    SelectList thelist = listwithselect ?? filter.SelectList;
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Shared\_Filter.cshtml"
Write(Html.DropDownList(filter.PropertyName, thelist, String.Empty, new {id = filter.PropertyName, @class = "form-control", onchange = "this.form.submit();"}));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Shared\_Filter.cshtml"
                                                                                                                                                             
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
