#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxBox.MVC.Views.Shared
{
    using System;
    
    #line 1 "..\..\Views\Shared\_Paging.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.IO;
    
    #line 2 "..\..\Views\Shared\_Paging.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\_Paging.cshtml"
    using MaxBox.MVC.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Paging.cshtml")]
    public partial class Paging : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Paging()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Shared\_Paging.cshtml"
  
    var pageProcessData = (PageProcessData) ViewBag.PagingVM;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\Shared\_Paging.cshtml"
 if (pageProcessData != null)
{
    if (pageProcessData.AuditPages != 1)
    {
        var pageList = new List<int>(pageProcessData.MaxPagination + 1);
        pageList.Add(pageProcessData.CurrentPage);
        for (int i = 1; i != pageProcessData.MaxPagination/2 + 1; i++)
        {
            pageList.Add(pageProcessData.CurrentPage - i);
            pageList.Add(pageProcessData.CurrentPage + i);
        }
        int prefirstpage = pageProcessData.CurrentPage - (pageProcessData.MaxPagination/2 + 1);
        int suffixlastpage = pageProcessData.CurrentPage + (pageProcessData.MaxPagination/2 + 1);

            
            #line default
            #line hidden
WriteLiteral("        <ul");

WriteLiteral(" class=\"pagination\"");

WriteLiteral(">\r\n");

            
            #line 21 "..\..\Views\Shared\_Paging.cshtml"
            
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Shared\_Paging.cshtml"
             if (pageProcessData.CurrentPage >= pageProcessData.MaxPagination)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li><a");

WriteAttribute("class", Tuple.Create(" class=\"", 920), Tuple.Create("\"", 981)
, Tuple.Create(Tuple.Create("", 928), Tuple.Create("btn", 928), true)
, Tuple.Create(Tuple.Create(" ", 931), Tuple.Create("btn-default", 932), true)
            
            #line 23 "..\..\Views\Shared\_Paging.cshtml"
, Tuple.Create(Tuple.Create(" ", 943), Tuple.Create<System.Object, System.Int32>(prefirstpage < 1 ? "disabled" : ""
            
            #line default
            #line hidden
, 944), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 982), Tuple.Create("\"", 1030)
            
            #line 23 "..\..\Views\Shared\_Paging.cshtml"
            , Tuple.Create(Tuple.Create(" ", 989), Tuple.Create<System.Object, System.Int32>(pageProcessData.GenerateUrlWithPage(1)
            
            #line default
            #line hidden
, 990), false)
, Tuple.Create(Tuple.Create(" ", 1029), Tuple.Create("", 1029), true)
);

WriteLiteral(">1</a></li>\r\n");

            
            #line 24 "..\..\Views\Shared\_Paging.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 25 "..\..\Views\Shared\_Paging.cshtml"
             if (pageProcessData.CurrentPage > pageProcessData.MaxPagination)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li><a");

WriteAttribute("class", Tuple.Create(" class=\"", 1175), Tuple.Create("\"", 1236)
, Tuple.Create(Tuple.Create("", 1183), Tuple.Create("btn", 1183), true)
, Tuple.Create(Tuple.Create(" ", 1186), Tuple.Create("btn-default", 1187), true)
            
            #line 27 "..\..\Views\Shared\_Paging.cshtml"
, Tuple.Create(Tuple.Create(" ", 1198), Tuple.Create<System.Object, System.Int32>(prefirstpage < 1 ? "disabled" : ""
            
            #line default
            #line hidden
, 1199), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 1237), Tuple.Create("\"", 1296)
            
            #line 27 "..\..\Views\Shared\_Paging.cshtml"
           , Tuple.Create(Tuple.Create(" ", 1244), Tuple.Create<System.Object, System.Int32>(pageProcessData.GenerateUrlWithPage(prefirstpage)
            
            #line default
            #line hidden
, 1245), false)
, Tuple.Create(Tuple.Create(" ", 1295), Tuple.Create("", 1295), true)
);

WriteLiteral(">...</a></li>\r\n");

            
            #line 28 "..\..\Views\Shared\_Paging.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 29 "..\..\Views\Shared\_Paging.cshtml"
             foreach (int pagenumber in pageList.OrderBy(x => x))
            {
                if (pagenumber > 0 && pagenumber <= pageProcessData.AuditPages)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n                        <a");

WriteAttribute("class", Tuple.Create(" class=\"", 1561), Tuple.Create("\"", 1678)
, Tuple.Create(Tuple.Create("", 1569), Tuple.Create("btn", 1569), true)
, Tuple.Create(Tuple.Create(" ", 1572), Tuple.Create("btn-default", 1573), true)
            
            #line 34 "..\..\Views\Shared\_Paging.cshtml"
, Tuple.Create(Tuple.Create(" ", 1584), Tuple.Create<System.Object, System.Int32>(pagenumber == (((int?) pageProcessData.CurrentPage).GetValueOrDefault(1)) ? "active" : ""
            
            #line default
            #line hidden
, 1585), false)
, Tuple.Create(Tuple.Create(" ", 1677), Tuple.Create("", 1677), true)
);

WriteAttribute("href", Tuple.Create(" href=\"", 1679), Tuple.Create("\"", 1736)
            
            #line 34 "..\..\Views\Shared\_Paging.cshtml"
                                                                       , Tuple.Create(Tuple.Create(" ", 1686), Tuple.Create<System.Object, System.Int32>(pageProcessData.GenerateUrlWithPage(pagenumber)
            
            #line default
            #line hidden
, 1687), false)
, Tuple.Create(Tuple.Create(" ", 1735), Tuple.Create("", 1735), true)
);

WriteLiteral(">");

            
            #line 34 "..\..\Views\Shared\_Paging.cshtml"
                                                                                                                                                                                                      Write(pagenumber.ToString());

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                    </li>\r\n");

            
            #line 36 "..\..\Views\Shared\_Paging.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 38 "..\..\Views\Shared\_Paging.cshtml"
             if (suffixlastpage < pageProcessData.AuditPages)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li><a");

WriteAttribute("class", Tuple.Create(" class=\"", 1927), Tuple.Create("\"", 2015)
, Tuple.Create(Tuple.Create("", 1935), Tuple.Create("btn", 1935), true)
, Tuple.Create(Tuple.Create(" ", 1938), Tuple.Create("btn-default", 1939), true)
            
            #line 40 "..\..\Views\Shared\_Paging.cshtml"
, Tuple.Create(Tuple.Create(" ", 1950), Tuple.Create<System.Object, System.Int32>(suffixlastpage > pageProcessData.AuditPages ? "disabled" : ""
            
            #line default
            #line hidden
, 1951), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 2016), Tuple.Create("\"", 2077)
            
            #line 40 "..\..\Views\Shared\_Paging.cshtml"
                                      , Tuple.Create(Tuple.Create(" ", 2023), Tuple.Create<System.Object, System.Int32>(pageProcessData.GenerateUrlWithPage(suffixlastpage)
            
            #line default
            #line hidden
, 2024), false)
, Tuple.Create(Tuple.Create(" ", 2076), Tuple.Create("", 2076), true)
);

WriteLiteral(">...</a></li>\r\n");

            
            #line 41 "..\..\Views\Shared\_Paging.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 42 "..\..\Views\Shared\_Paging.cshtml"
             if (pageProcessData.AuditPages > pageProcessData.CurrentPage)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li><a");

WriteAttribute("class", Tuple.Create(" class=\"", 2221), Tuple.Create("\"", 2309)
, Tuple.Create(Tuple.Create("", 2229), Tuple.Create("btn", 2229), true)
, Tuple.Create(Tuple.Create(" ", 2232), Tuple.Create("btn-default", 2233), true)
            
            #line 44 "..\..\Views\Shared\_Paging.cshtml"
, Tuple.Create(Tuple.Create(" ", 2244), Tuple.Create<System.Object, System.Int32>(suffixlastpage > pageProcessData.AuditPages ? "disabled" : ""
            
            #line default
            #line hidden
, 2245), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 2310), Tuple.Create("\"", 2383)
            
            #line 44 "..\..\Views\Shared\_Paging.cshtml"
                                      , Tuple.Create(Tuple.Create(" ", 2317), Tuple.Create<System.Object, System.Int32>(pageProcessData.GenerateUrlWithPage(pageProcessData.AuditPages)
            
            #line default
            #line hidden
, 2318), false)
, Tuple.Create(Tuple.Create(" ", 2382), Tuple.Create("", 2382), true)
);

WriteLiteral(">");

            
            #line 44 "..\..\Views\Shared\_Paging.cshtml"
                                                                                                                                                                                     Write(pageProcessData.AuditPages);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 45 "..\..\Views\Shared\_Paging.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n");

            
            #line 47 "..\..\Views\Shared\_Paging.cshtml"
    }
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
