#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxBox.MVC.Views.Shared
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Shared\_Paging.cshtml"
    using System.Diagnostics;
    
    #line default
    #line hidden
    using System.IO;
    
    #line 2 "..\..\Views\Shared\_Paging.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\_Paging.cshtml"
    using MaxBox.MVC.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Paging.cshtml")]
    public partial class Paging : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Paging()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Shared\_Paging.cshtml"
  
    var pageProcessData = (PageProcessData)ViewBag.PageData;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\Shared\_Paging.cshtml"
 if (pageProcessData != null)
{
    if (pageProcessData.AuditPages != 1)
    {
        var pageList = new List<int>(pageProcessData.MaxPagination + 1);
        pageList.Add(pageProcessData.CurrentPage);
        for (int i = 1; i != pageProcessData.MaxPagination / 2 + 1; i++)
        {
            pageList.Add(pageProcessData.CurrentPage - i);
            pageList.Add(pageProcessData.CurrentPage + i);
        }
        int prefirstpage = pageProcessData.CurrentPage - (pageProcessData.MaxPagination / 2 + 1);
        int suffixlastpage = pageProcessData.CurrentPage + (pageProcessData.MaxPagination / 2 + 1);
        Debugger.Launch();

            
            #line default
            #line hidden
WriteLiteral("        <ul");

WriteLiteral(" class=\"pagination\"");

WriteLiteral(">\r\n");

            
            #line 22 "..\..\Views\Shared\_Paging.cshtml"
            
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Shared\_Paging.cshtml"
             if (pageProcessData.CurrentPage >= pageProcessData.MaxPagination)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li><a");

WriteAttribute("class", Tuple.Create(" class=\"", 945), Tuple.Create("\"", 1006)
, Tuple.Create(Tuple.Create("", 953), Tuple.Create("btn", 953), true)
, Tuple.Create(Tuple.Create(" ", 956), Tuple.Create("btn-default", 957), true)
            
            #line 24 "..\..\Views\Shared\_Paging.cshtml"
, Tuple.Create(Tuple.Create(" ", 968), Tuple.Create<System.Object, System.Int32>(prefirstpage < 1 ? "disabled" : ""
            
            #line default
            #line hidden
, 969), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 1007), Tuple.Create("\"", 1055)
            
            #line 24 "..\..\Views\Shared\_Paging.cshtml"
           , Tuple.Create(Tuple.Create(" ", 1014), Tuple.Create<System.Object, System.Int32>(pageProcessData.GenerateUrlWithPage(1)
            
            #line default
            #line hidden
, 1015), false)
, Tuple.Create(Tuple.Create(" ", 1054), Tuple.Create("", 1054), true)
);

WriteLiteral(">1</a></li>\r\n");

            
            #line 25 "..\..\Views\Shared\_Paging.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 26 "..\..\Views\Shared\_Paging.cshtml"
             if (pageProcessData.CurrentPage >= pageProcessData.MaxPagination)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li><a");

WriteAttribute("class", Tuple.Create(" class=\"", 1201), Tuple.Create("\"", 1262)
, Tuple.Create(Tuple.Create("", 1209), Tuple.Create("btn", 1209), true)
, Tuple.Create(Tuple.Create(" ", 1212), Tuple.Create("btn-default", 1213), true)
            
            #line 28 "..\..\Views\Shared\_Paging.cshtml"
, Tuple.Create(Tuple.Create(" ", 1224), Tuple.Create<System.Object, System.Int32>(prefirstpage < 1 ? "disabled" : ""
            
            #line default
            #line hidden
, 1225), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 1263), Tuple.Create("\"", 1322)
            
            #line 28 "..\..\Views\Shared\_Paging.cshtml"
           , Tuple.Create(Tuple.Create(" ", 1270), Tuple.Create<System.Object, System.Int32>(pageProcessData.GenerateUrlWithPage(prefirstpage)
            
            #line default
            #line hidden
, 1271), false)
, Tuple.Create(Tuple.Create(" ", 1321), Tuple.Create("", 1321), true)
);

WriteLiteral(">...</a></li>\r\n");

            
            #line 29 "..\..\Views\Shared\_Paging.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 30 "..\..\Views\Shared\_Paging.cshtml"
             foreach (int pagenumber in pageList.OrderBy(x => x))
            {
                if (pagenumber > 0 && pagenumber <= pageProcessData.AuditPages)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n                        <a");

WriteAttribute("class", Tuple.Create(" class=\"", 1587), Tuple.Create("\"", 1704)
, Tuple.Create(Tuple.Create("", 1595), Tuple.Create("btn", 1595), true)
, Tuple.Create(Tuple.Create(" ", 1598), Tuple.Create("btn-default", 1599), true)
            
            #line 35 "..\..\Views\Shared\_Paging.cshtml"
, Tuple.Create(Tuple.Create(" ", 1610), Tuple.Create<System.Object, System.Int32>(pagenumber == (((int?) pageProcessData.CurrentPage).GetValueOrDefault(1)) ? "active" : ""
            
            #line default
            #line hidden
, 1611), false)
, Tuple.Create(Tuple.Create(" ", 1703), Tuple.Create("", 1703), true)
);

WriteAttribute("href", Tuple.Create(" href=\"", 1705), Tuple.Create("\"", 1762)
            
            #line 35 "..\..\Views\Shared\_Paging.cshtml"
                                                                       , Tuple.Create(Tuple.Create(" ", 1712), Tuple.Create<System.Object, System.Int32>(pageProcessData.GenerateUrlWithPage(pagenumber)
            
            #line default
            #line hidden
, 1713), false)
, Tuple.Create(Tuple.Create(" ", 1761), Tuple.Create("", 1761), true)
);

WriteLiteral(">");

            
            #line 35 "..\..\Views\Shared\_Paging.cshtml"
                                                                                                                                                                                                      Write(pagenumber.ToString());

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                    </li>\r\n");

            
            #line 37 "..\..\Views\Shared\_Paging.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 39 "..\..\Views\Shared\_Paging.cshtml"
             if (suffixlastpage < pageProcessData.AuditPages)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li><a");

WriteAttribute("class", Tuple.Create(" class=\"", 1953), Tuple.Create("\"", 2041)
, Tuple.Create(Tuple.Create("", 1961), Tuple.Create("btn", 1961), true)
, Tuple.Create(Tuple.Create(" ", 1964), Tuple.Create("btn-default", 1965), true)
            
            #line 41 "..\..\Views\Shared\_Paging.cshtml"
, Tuple.Create(Tuple.Create(" ", 1976), Tuple.Create<System.Object, System.Int32>(suffixlastpage > pageProcessData.AuditPages ? "disabled" : ""
            
            #line default
            #line hidden
, 1977), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 2042), Tuple.Create("\"", 2103)
            
            #line 41 "..\..\Views\Shared\_Paging.cshtml"
                                      , Tuple.Create(Tuple.Create(" ", 2049), Tuple.Create<System.Object, System.Int32>(pageProcessData.GenerateUrlWithPage(suffixlastpage)
            
            #line default
            #line hidden
, 2050), false)
, Tuple.Create(Tuple.Create(" ", 2102), Tuple.Create("", 2102), true)
);

WriteLiteral(">...</a></li>\r\n");

            
            #line 42 "..\..\Views\Shared\_Paging.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 43 "..\..\Views\Shared\_Paging.cshtml"
             if (suffixlastpage <= pageProcessData.AuditPages)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li><a");

WriteAttribute("class", Tuple.Create(" class=\"", 2235), Tuple.Create("\"", 2323)
, Tuple.Create(Tuple.Create("", 2243), Tuple.Create("btn", 2243), true)
, Tuple.Create(Tuple.Create(" ", 2246), Tuple.Create("btn-default", 2247), true)
            
            #line 45 "..\..\Views\Shared\_Paging.cshtml"
, Tuple.Create(Tuple.Create(" ", 2258), Tuple.Create<System.Object, System.Int32>(suffixlastpage > pageProcessData.AuditPages ? "disabled" : ""
            
            #line default
            #line hidden
, 2259), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 2324), Tuple.Create("\"", 2397)
            
            #line 45 "..\..\Views\Shared\_Paging.cshtml"
                                      , Tuple.Create(Tuple.Create(" ", 2331), Tuple.Create<System.Object, System.Int32>(pageProcessData.GenerateUrlWithPage(pageProcessData.AuditPages)
            
            #line default
            #line hidden
, 2332), false)
, Tuple.Create(Tuple.Create(" ", 2396), Tuple.Create("", 2396), true)
);

WriteLiteral(">");

            
            #line 45 "..\..\Views\Shared\_Paging.cshtml"
                                                                                                                                                                                     Write(pageProcessData.AuditPages);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 46 "..\..\Views\Shared\_Paging.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n");

            
            #line 48 "..\..\Views\Shared\_Paging.cshtml"
    }
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
